name: visora_ai_flutter
description: Visora â€“ Ultimate AI Video Studio
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # âš™ï¸ HTTP Requests (Backend Communication)
  http: ^0.13.6

  # ðŸŽ™ï¸ File Picker (Voice Uploads)
  file_picker: ^5.2.4

  # ðŸ“· Image Picker (optional for thumbnails)
  image_picker: ^0.8.7+5

  # ðŸ§© Lottie Animations
  lottie: ^2.3.2

  # ðŸ§  Flutter SVG (for vector icons)
  flutter_svg: ^1.1.6

  # âœï¸ Fonts
  google_fonts: ^4.0.4

  # ðŸŒˆ Image Parser / Filters (for later filters & effects)
  image: ^4.0.17
  http_parser: ^4.0.2
  blur: ^3.1.0

  # ðŸŒ URL Launcher (To open video links)
  url_launcher: ^6.1.7

  # ðŸ“ Path Provider (optional caching)
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/loading.json
    - assets/lottie/done.json
    - assets/logo/visora_logo.png
    - assets/logo/visora_logo_splash.png
    - assets/logo/visora_logo_white.png
    - assets/logo/visora_logo_dark.png
    - assets/logo/visora_full_text.png
    - assets/logo/visora_brand_banner.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/visora_logo.png"
